# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_item_items_customer_id_delete(self) -> None:
        """Test case for delete_item_items_customer_id_delete

        Delete Item
        """
        pass

    def test_deregister_cluster_node_cluster_node_ip_delete(self) -> None:
        """Test case for deregister_cluster_node_cluster_node_ip_delete

        Deregister Cluster Node
        """
        pass

    def test_health_check_health_check_customer_id_get(self) -> None:
        """Test case for health_check_health_check_customer_id_get

        Health Check
        """
        pass

    def test_put_item_items_customer_id_put(self) -> None:
        """Test case for put_item_items_customer_id_put

        Put Item
        """
        pass

    def test_read_cluster_status_cluster_get(self) -> None:
        """Test case for read_cluster_status_cluster_get

        Read Cluster Status
        """
        pass

    def test_read_customer_cluster_status_cluster_customer_id_get(self) -> None:
        """Test case for read_customer_cluster_status_cluster_customer_id_get

        Read Customer Cluster Status
        """
        pass

    def test_read_item_item_customer_id_id_get(self) -> None:
        """Test case for read_item_item_customer_id_id_get

        Read Item
        """
        pass

    def test_read_items_items_customer_id_get(self) -> None:
        """Test case for read_items_items_customer_id_get

        Read Items
        """
        pass

    def test_register_cluster_node_cluster_customer_id_put(self) -> None:
        """Test case for register_cluster_node_cluster_customer_id_put

        Register Cluster Node
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
